name: Test

on: 
  push:
  pull_request:
  repository_dispatch:
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: set
      run: git_hash=$(git rev-parse --short "$GITHUB_SHA") && git_branch=${GITHUB_REF#refs/heads/}
    - name: Test
      run: sudo ./test.sh ${git_hash} ${git_branch}